FROM tensorflow/tensorflow:2.4.0-gpu-jupyter

RUN pip install qiskit qiskit-aer-gpu numba matplotlib jupyterlab

EXPOSE 8888

RUN useradd -ms /bin/bash quantum
USER quantum
WORKDIR /home/quantum

COPY test-statevector.py /home/quantum/

RUN git clone https://github.com/yiiyama/qc_random

#CMD ["jupyter", "lab", "--no-browser"]
